// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7e9MTSWUNjScHg4kGsDW6Lw7RWQ8W-iU',
    appId: '1:1008520165269:web:0681b4247d73e7ea52289c',
    messagingSenderId: '1008520165269',
    projectId: 'chatup-ca586',
    authDomain: 'chatup-ca586.firebaseapp.com',
    storageBucket: 'chatup-ca586.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwgDF-bGe_aHOhWqzLhS0xW9Hc0lXLvq8',
    appId: '1:1008520165269:android:82858bbd915d745352289c',
    messagingSenderId: '1008520165269',
    projectId: 'chatup-ca586',
    storageBucket: 'chatup-ca586.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX9cPy5f93H52gSR5XGzxxlwHbRe2OwWQ',
    appId: '1:1008520165269:ios:e3fd924f0df02c1452289c',
    messagingSenderId: '1008520165269',
    projectId: 'chatup-ca586',
    storageBucket: 'chatup-ca586.firebasestorage.app',
    iosBundleId: 'com.example.chatup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX9cPy5f93H52gSR5XGzxxlwHbRe2OwWQ',
    appId: '1:1008520165269:ios:e3fd924f0df02c1452289c',
    messagingSenderId: '1008520165269',
    projectId: 'chatup-ca586',
    storageBucket: 'chatup-ca586.firebasestorage.app',
    iosBundleId: 'com.example.chatup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7e9MTSWUNjScHg4kGsDW6Lw7RWQ8W-iU',
    appId: '1:1008520165269:web:47280c9064444b2a52289c',
    messagingSenderId: '1008520165269',
    projectId: 'chatup-ca586',
    authDomain: 'chatup-ca586.firebaseapp.com',
    storageBucket: 'chatup-ca586.firebasestorage.app',
  );
}
